name: ui_templates
description: UI 模版库 - 页面框架、布局、组件模版
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: ^3.27.0

dependencies:
  flutter:
    sdk: flutter

  # 瀑布流布局
  flutter_staggered_grid_view: ^0.7.0

  # Core dependencies
  core_base:
    path: ../../core/core_base
  core_utils:
    path: ../../core/core_utils

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
